{{- range .Values.applications }}
{{- if .configMaps }}
{{- range .configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" $ }}-{{ .name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $.name }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
