{{- $resourceProfiles := .Files.Get "configurations/resources.yaml" | fromYaml }}
{{- range .Values.applications }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" $ }}-{{ .name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .replicaCount | default $.Values.common.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.appSelectorLabel" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "common.appSelectorLabel" . | nindent 8 }}
        app.kubernetes.io/component: {{ .name }}
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "common.serviceAccountName" (dict "serviceAccount" .serviceAccount "name" .name "Values" $.Values) }}
      {{- if .initContainers }}
      initContainers:
        {{- toYaml .initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.common.imageRegistry }}/{{ $.Values.common.imageProject }}/{{ .image.repository }}:{{ .image.tag | default "latest" }}"
          imagePullPolicy: {{ .imagePullPolicy | default $.Values.common.imagePullPolicy }}
          ports:
            {{- with .ports }}
            {{- toYaml . | nindent 12 }}
            {{- else }}
            - name: http
              containerPort: 8080
              protocol: TCP
            {{- end }}
          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- if .resources }}
            {{- toYaml .resources | nindent 12 }}
            {{- else if .resourceProfile }}
            {{- $profile := .resourceProfile }}
            {{- with (index $resourceProfiles.resourceProfiles $profile) }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- else }}
            {{- toYaml $.Values.common.resources | nindent 12 }}
            {{- end }}
          {{- if .livenessProbe }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .podAntiAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - {{ .name }}
              topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- if .topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if or .configMaps .secrets .pvc .volumes }}
      volumes:
        {{- if .volumes }}
        {{- toYaml .volumes | nindent 8 }}
        {{- end }}
        {{- range .configMaps }}
        - name: {{ .name }}
          configMap:
            name: {{ include "common.fullname" $ }}-{{ .name }}
        {{- end }}
        {{- range .secrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ include "common.fullname" $ }}-{{ .name }}
        {{- end }}
        {{- range .pvc }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "common.fullname" $ }}-{{ .name }}
        {{- end }}
      {{- end }}
{{- end }}