{{- range .Values.applications }}
{{- if .pvc }}
{{- range .pvc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.fullname" $ }}-{{ .name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $.name }}
spec:
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass }}
{{- end }}
{{- end }}
{{- end }}
